
// Get the employee with version 1.0.0

GET http://localhost:3000/rpc/getEmployee?id=1 HTTP/1.1
X-Jitar-Procedure-Version: 1.0.0

###

// Get the employee with version 2.0.0

GET http://localhost:3000/rpc/getEmployee?uuid=f507cf82-ca51-4a42-8c20-ce5c7c42a77e HTTP/1.1
X-Jitar-Procedure-Version: 2.0.0
X-Jitar-Trust-Key: MY_VERY_SECRET_KEY
