# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Maintain dependencies for jitar
  - package-ecosystem: "npm"
    directory: "/jitar"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "npm"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      separator: "-"
    reviewers:
      - "basmasking"
      - "petermasking"