version: '3'

services:

    jitar-documentation:
        container_name: jitar-docs
        image: jitardocs
        build:
          context: ./
          dockerfile: ./Dockerfile
        restart: 'unless-stopped'
        command: 'jekyll serve'
        ports:
            - 4000:4000
        volumes:
            - "../:/srv/jekyll"
