
// Register John Doe for an account
// This will return the registration information as a string

GET http://localhost:3000/rpc/helpdesk/register?firstName=John&lastName=Doe HTTP/1.1

###

// Create an account for John Doe
// This will return the serialized account object

GET http://localhost:3000/rpc/account/createAccount?firstName=John&lastName=Doe&serialize=true HTTP/1.1 
