
// Add

POST http://localhost:3000/rpc/calculator/add HTTP/1.1
content-type: application/json

{
    "first": 15,
    "second": 27
}

###

// Subtract

POST http://localhost:3000/rpc/calculator/subtract HTTP/1.1
content-type: application/json

{
    "first": 48,
    "second": 6
}

###

// Multiply

POST http://localhost:3000/rpc/calculator/multiply HTTP/1.1
content-type: application/json

{
    "first": 5,
    "second": 5
}

###

// Divide

POST http://localhost:3000/rpc/calculator/divide HTTP/1.1
content-type: application/json

{
    "first": 42,
    "second": 6
}
