
// Run the public function (succeeds)

GET http://localhost:3000/rpc/web/guessSecret?secret=123

###

// Run the protected function with key (succeeds)
GET http://localhost:3000/rpc/game/checkSecret?secret=123 HTTP/1.1
x-access-key: VERY_SECRET_KEY

###

// Run the protected function without key (fails -> 401)
GET http://localhost:3000/rpc/game/checkSecret?secret=123 HTTP/1.1

###

// Run the private function (fails -> 404)

GET http://localhost:3000/rpc/game/getSecret HTTP/1.1
