
// Get the employee details without any version (defaults to version 0.0.0)

GET http://localhost:3000/rpc/employee/getEmployeeDetails?id=1 HTTP/1.1

###

// Get the employee details with version 1.0.0

GET http://localhost:3000/rpc/employee/getEmployeeDetails?version=1.0.0&id=1 HTTP/1.1

###

// Get the organization details with version 0.0.0

GET http://localhost:3000/rpc/organization/getOrganizationDetails?version=0.0.0&id=2 HTTP/1.1

###

// Get the organization details with version 1.0.0

GET http://localhost:3000/rpc/organization/getOrganizationDetails?version=1.0.0&id=2 HTTP/1.1
