
// The database error is caught and printed to the console.

GET http://localhost:3000/rpc/getData HTTP/1.1

###

// The database error is uncaught and send as reponse.

GET http://localhost:3000/rpc/exportData HTTP/1.1
