
GET http://localhost:8080/rpc/domain/contact/getContacts?version=0.0.0&serialize=true HTTP/1.1

###

GET http://localhost:3000/rpc/domain/contact/getContacts?version=0.0.0&serialize=true HTTP/1.1

###

GET http://localhost:3000/abc HTTP/1.1
