
// Get the data (from the data segment)

GET http://localhost:3000/rpc/reporting/getData HTTP/1.1

###

// Create the statistics (from the process segment)

POST http://localhost:3000/rpc/reporting/createStatistics HTTP/1.1
content-type: application/json

{
    "data": [1, 2, 3, 4, 5]
}

###

// Create the report (from both segments)

GET http://localhost:3000/rpc/reporting/createReport HTTP/1.1
